apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260619-190212-k07xjdovjl51-service
spec:
  selector:
    app: enterprise-system-20260619-190212-k07xjdovjl51
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
